version: "3.4"

services:
  urbanknowledgegraphsite:
    container_name: ukgsite
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv/node_modules
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"
